//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Eventos_web_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RecursoXPaquete
    {
        public int id { get; set; }
        [DisplayName("Paquete")]
        public int idPaquete { get; set; }
        [DisplayName("Recurso")]
        public int idRecurso { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
