//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_Eventos_web_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservacion
    {
        public int id { get; set; }
        [DisplayName("Fecha")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha { get; set; }
        [DisplayName("Cliente")]
        public int idCliente { get; set; }
        [DisplayName("Paquete")]
        public int idPaquete { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Paquete Paquete { get; set; }
    }
}
