//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Recurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurso()
        {
            this.RecursoXPaquete = new HashSet<RecursoXPaquete>();
        }

        [DisplayName("Id")]
        public int id { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("e-mail")]
        public string correo { get; set; }
        [DisplayName("Telefono")]
        public string telefono { get; set; }
        [DisplayName("Ubicacion")]
        public string ubicacion { get; set; }
        [DisplayName("Estado")]
        public string estado { get; set; }
        public int idTipoRecurso { get; set; }
    
        public virtual TipoRecurso TipoRecurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecursoXPaquete> RecursoXPaquete { get; set; }
    }
}
